create extension if not exists pgcrypto;
create type public.trip_status as enum ('active','archived');
create type public.item_status as enum ('not_bought','bought');

create table public.trips(id uuid primary key default gen_random_uuid(),share_token text unique not null default encode(gen_random_bytes(18),'hex'),name text not null check(length(name) between 1 and 100),start_date date not null,end_date date not null check(end_date>=start_date),status trip_status not null default 'active',created_by uuid,created_at timestamptz not null default now(),archived_at timestamptz);
create table public.participants(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips on delete cascade,user_id uuid not null references auth.users on delete cascade,display_name text not null check(length(display_name) between 2 and 60),is_admin boolean not null default false,created_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),unique(trip_id,user_id));
alter table public.trips add constraint trips_created_by_fkey foreign key(created_by) references public.participants(id) on delete set null;
create table public.meals(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips on delete cascade,date date not null,meal_type text not null check(meal_type in('breakfast','lunch','dinner','other')),title text not null,notes text,created_by uuid references public.participants,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.meal_ingredients(id uuid primary key default gen_random_uuid(),meal_id uuid not null references public.meals on delete cascade,name text not null,quantity numeric not null default 1 check(quantity>0),unit text,added_to_shopping boolean not null default false,created_by uuid references public.participants,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.shopping_items(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips on delete cascade,name text not null,quantity numeric not null default 1 check(quantity>0),unit text,category text not null check(category in('food','drinks','boat','other')),meal_id uuid references public.meals on delete set null,meal_ingredient_id uuid references public.meal_ingredients on delete set null,status item_status not null default 'not_bought',bought_by uuid references public.participants on delete set null,created_by uuid references public.participants,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1);
create table public.audit_log(id bigint generated always as identity primary key,trip_id uuid not null references public.trips on delete cascade,created_at timestamptz not null default now(),participant_id uuid references public.participants on delete set null,participant_name text,action_type text not null,entity_type text not null,entity_id text,old_value jsonb,new_value jsonb,metadata jsonb not null default '{}'::jsonb);

create or replace function public.is_member(t uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from participants where trip_id=t and user_id=auth.uid())$$;
create or replace function public.is_admin(t uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from participants where trip_id=t and user_id=auth.uid() and is_admin)$$;
create or replace function public.trip_active(t uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from trips where id=t and status='active')$$;

alter table public.trips enable row level security;alter table public.participants enable row level security;alter table public.meals enable row level security;alter table public.meal_ingredients enable row level security;alter table public.shopping_items enable row level security;alter table public.audit_log enable row level security;
create policy "trip via member or token lookup" on public.trips for select to authenticated using(is_member(id) or share_token is not null);
create policy "members read participants" on public.participants for select to authenticated using(is_member(trip_id) or user_id=auth.uid());
create policy "members edit meals" on public.meals for all to authenticated using(is_member(trip_id) and trip_active(trip_id)) with check(is_member(trip_id) and trip_active(trip_id));
create policy "members read meals" on public.meals for select to authenticated using(is_member(trip_id));
create policy "members edit ingredients" on public.meal_ingredients for all to authenticated using(exists(select 1 from meals m where m.id=meal_id and is_member(m.trip_id) and trip_active(m.trip_id))) with check(exists(select 1 from meals m where m.id=meal_id and is_member(m.trip_id) and trip_active(m.trip_id)));
create policy "members read ingredients" on public.meal_ingredients for select to authenticated using(exists(select 1 from meals m where m.id=meal_id and is_member(m.trip_id)));
create policy "members edit shopping" on public.shopping_items for all to authenticated using(is_member(trip_id) and trip_active(trip_id)) with check(is_member(trip_id) and trip_active(trip_id));
create policy "members read shopping" on public.shopping_items for select to authenticated using(is_member(trip_id));
create policy "admins read audit" on public.audit_log for select to authenticated using(is_admin(trip_id));

create or replace function public.create_trip(p_name text,p_start_date date,p_end_date date,p_display_name text) returns public.trips language plpgsql security definer set search_path=public as $$declare t trips;p participants;begin if auth.uid() is null then raise exception 'Authentication required';end if;insert into trips(name,start_date,end_date) values(trim(p_name),p_start_date,p_end_date) returning * into t;insert into participants(trip_id,user_id,display_name,is_admin) values(t.id,auth.uid(),trim(p_display_name),true) returning * into p;update trips set created_by=p.id where id=t.id returning * into t;insert into audit_log(trip_id,participant_id,participant_name,action_type,entity_type,entity_id,new_value) values(t.id,p.id,p.display_name,'trip_created','trip',t.id::text,to_jsonb(t));return t;end$$;
create or replace function public.join_trip(p_share_token text,p_display_name text) returns public.participants language plpgsql security definer set search_path=public as $$declare t trips;p participants;begin select * into t from trips where share_token=p_share_token;if not found then raise exception 'Plovba ne obstaja';end if;insert into participants(trip_id,user_id,display_name) values(t.id,auth.uid(),trim(p_display_name)) on conflict(trip_id,user_id) do update set display_name=excluded.display_name,last_seen_at=now() returning * into p;insert into audit_log(trip_id,participant_id,participant_name,action_type,entity_type,entity_id,new_value) values(t.id,p.id,p.display_name,'participant_joined','participant',p.id::text,to_jsonb(p));return p;end$$;
create or replace function public.add_meal_ingredients_to_shopping(p_meal_id uuid,p_participant_id uuid) returns integer language plpgsql security definer set search_path=public as $$declare m meals;n integer;begin select * into m from meals where id=p_meal_id;if not is_member(m.trip_id) or not trip_active(m.trip_id) then raise exception 'Not allowed';end if;if not exists(select 1 from participants where id=p_participant_id and user_id=auth.uid() and trip_id=m.trip_id) then raise exception 'Invalid participant';end if;insert into shopping_items(trip_id,name,quantity,unit,category,meal_id,meal_ingredient_id,created_by) select m.trip_id,i.name,i.quantity,i.unit,'food',m.id,i.id,p_participant_id from meal_ingredients i where i.meal_id=m.id and not i.added_to_shopping;get diagnostics n=row_count;update meal_ingredients set added_to_shopping=true where meal_id=m.id and not added_to_shopping;return n;end$$;
create or replace function public.set_item_bought(p_item_id uuid,p_participant_id uuid,p_bought boolean,p_expected_version integer) returns public.shopping_items language plpgsql security definer set search_path=public as $$declare old shopping_items;new shopping_items;p participants;begin select * into old from shopping_items where id=p_item_id for update;if not trip_active(old.trip_id) then raise exception 'Archived';end if;select * into p from participants where id=p_participant_id and user_id=auth.uid() and trip_id=old.trip_id;if not found then raise exception 'Invalid participant';end if;if old.version<>p_expected_version then raise exception 'Version conflict';end if;update shopping_items set status=case when p_bought then 'bought'::item_status else 'not_bought'::item_status end,bought_by=case when p_bought then p.id else null end,version=version+1,updated_at=now() where id=p_item_id returning * into new;insert into audit_log(trip_id,participant_id,participant_name,action_type,entity_type,entity_id,old_value,new_value) values(old.trip_id,p.id,p.display_name,case when p_bought then 'shopping_item_bought' else 'shopping_item_unbought' end,'shopping_item',old.id::text,to_jsonb(old),to_jsonb(new));return new;end$$;
create or replace function public.archive_trip(p_trip_id uuid) returns void language plpgsql security definer set search_path=public as $$declare p participants;begin select * into p from participants where trip_id=p_trip_id and user_id=auth.uid() and is_admin;if not found then raise exception 'Admin required';end if;update trips set status='archived',archived_at=now() where id=p_trip_id;insert into audit_log(trip_id,participant_id,participant_name,action_type,entity_type,entity_id) values(p_trip_id,p.id,p.display_name,'trip_archived','trip',p_trip_id::text);end$$;
grant execute on function public.create_trip(text,date,date,text),public.join_trip(text,text),public.add_meal_ingredients_to_shopping(uuid,uuid),public.set_item_bought(uuid,uuid,boolean,integer),public.archive_trip(uuid) to authenticated;
alter publication supabase_realtime add table public.participants,public.meals,public.meal_ingredients,public.shopping_items;
